# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4deda7b8bd1b0ec5f29549a9da2434fb55a5a9724c8b968dd30fbe955d196e46f808e1c1ecc044492ef7aa054cb0ee60780b09720d58d13ff8123f3db37cdc52

test:
  secret_key_base: c12dcfd9f435504495540968a7aab4fe2968f840fccbe34b08af8f31c1c6aba38aac147912e3a1649c736180e5ea2f820b756338e24c75c5115d8e56ecf1ebf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
